added coc command
ILUGD/ilugd-bot pull request #5
Opened 2019-02-04 14:52 UTC by ajax711

2019-02-04 14:55 UTC, rajudev reviewed
Line number 8 in bot.ini

2019-02-04 14:56 UTC, hellozee requested changes
Apart from that single change, the patch looks fine, though can't merge it currently since the COC is still a WIP, has many flaws, as soon as the COC gets finalized, this PR can be merged, :smile_cat:

2019-02-04 14:56 UTC, hellozee commented on bot.ini
> +github=https://github.com/ILUG
```suggestion
github=https://github.com/ILUGD
```

2019-02-06 03:52 UTC, hellozee approved these changes

2019-09-16 12:52 UTC, merged